FROM flink:2.0.0-scala_2.12-java17

# Install Python 3 and pip for PyFlink support
RUN apt-get update -y && \
    apt-get install -y python3 python3-pip python3-dev && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    rm -rf /var/lib/apt/lists/*

# Set Flink lib directory
ENV FLINK_LIB_DIR=/opt/flink/lib

# Clean up any pre-installed Kafka connector or related JARs to avoid conflicts
RUN rm -f ${FLINK_LIB_DIR}/flink-connector-kafka* ${FLINK_LIB_DIR}/kafka-clients*

# Download flink-connector-kafka for Flink 2.0.0 (version 4.0.0-2.0)
RUN curl -fSL \
  https://repo1.maven.org/maven2/org/apache/flink/flink-connector-kafka/4.0.0-2.0/flink-connector-kafka-4.0.0-2.0.jar \
  -o ${FLINK_LIB_DIR}/flink-connector-kafka-4.0.0-2.0.jar && \
  chmod 644 ${FLINK_LIB_DIR}/flink-connector-kafka-4.0.0-2.0.jar

# Download compatible kafka-clients (version 3.4.1)
RUN curl -fSL \
  https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.4.1/kafka-clients-3.4.1.jar \
  -o ${FLINK_LIB_DIR}/kafka-clients-3.4.1.jar && \
  chmod 644 ${FLINK_LIB_DIR}/kafka-clients-3.4.1.jar