FROM flink:1.17

USER root

# Install Python and pip
RUN apt-get update && apt-get install -y python3 python3-pip \
    && pip3 install apache-flink==1.17.1

# Add Kafka connector JAR
ADD https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-kafka/1.17.1/flink-sql-connector-kafka-1.17.1.jar /opt/flink/lib/

USER flink
